### ISSUE TITLE
review source code license

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#39]
Review and ensure the repo has a license and it follows LINZ and government licensing best practice

**Comment by SPlanzer** [comment]
* Currently the project is under the 3-clause BSD License
* This may be an issue as the project redistributes geoalchemy that is MIT. 

This repo is currently open and a discuss around license is required

**Comment by billgeo** [comment]
Interesting that it is open. Not sure what value there is in that, but would be interested to know.

**Comment by palmerj** [comment]
> This may be an issue as the project redistributes geoalchemy that is MIT.

It not an issue if the licence is clearly stated in the files that are not BSD. 

> Interesting that it is open. Not sure what value there is in that, but would be interested to know.

Of course, it's best if government makes its source code open, unless there is a reason not to. But I think it's open because NZGB wanted to allow other international agencies to see it. We have opened up the website source code as well.

**Comment by palmerj** [comment]
If we want we can move this repos to MIT. That's the recommended licence for open source code in NZ now.

**Comment by SPlanzer** [comment]
> If we want we can move this repos to MIT. That's the recommended licence for open source code in NZ now.

Great will do

**Comment by SPlanzer** [comment]
Done
