### ISSUE TITLE
Where should user docs live?

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#48]
Currently user documentation lives down in: 
* `https://github.com/linz/gazetteer/blob/master/src/NZGBplugin/help/index.html`

It is standard to have user documentation in confluence. 

discussion Require
* Does the NZGB require this migrated to confluence?
* Is it complete?
* Who is best to do the above?

**Comment by billgeo** [comment]
I would say yes, to moving it to Confluence. Because; a) NZGB can modify as they see fit b) can be linked to other documentation, c) is standard for other LINZ apps 
Downside is any public users/forkers couldn't access this, but may be resolved by https://github.com/linz/gazetteer/issues/39

Chris would be best to do the confluence work I think.

**Comment by palmerj** [comment]
> Currently user documentation lives down in:

Note it lives there because that's the standard place for QGIS plugins (or was at the time), and there are API for showing it within plugins.

Because there is not going to be a need for parallel version of plugin docs, its ok to port it to confluence for the reasons Bill mentioned. But you will need to have some sort of status section in the docs so users are clear which version of the software it applies. I can imagery some users might not upgrade the plugin straight away, or the user docs are not updated at the time of release.

**Comment by SPlanzer** [comment]
> Note it lives there because that's the standard place for QGIS plugins (or was at the time), and there are API for showing it within plugins. 

Thanks @palmerj  
In this case I will close this issue. I think this current implementation of having the docs with the software is a good one

**Comment by billgeo** [comment]
Maybe NZGB can choose to add additional, or duplicated, documentation in confluence if they want to, and can be managed outside this project.
